struct song_node** create();
struct song_node** add_song(struct song_node** lib, char* s, char* a);
void print_letter(struct song_node** lib, char l);
int ind(char* a);
struct song_node* find_track(struct song_node** lib, char* s, char* a);
struct song_node* find_artist(struct song_node** lib, char* a);
int ind2(char a);
void print_artist(struct song_node** lib, char* a);
void print_lib(struct song_node** lib);
void shuffle_songs(struct song_node** lib);
struct song_node* rndm(struct song_node** lib);
struct song_node** remove_song(struct song_node** lib, char* s, char* a);
struct song_node** remove_all(struct song_node** lib);
